on: [push]
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ secrets.PROJECT_NAME }}'
        credentials_json: '${{ secrets.CREDENTIALS }}'


    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      timeout-minutes: 10
      with:
        name: '${{ secrets.FUNCTION_NAME }}'
        runtime: 'nodejs22'
        entry_point: 'screenshot'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
